/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanele
 */
public class Species extends javax.swing.JPanel {

    /**
     * Creates new form Species
     */
    public Species() {
        initComponents();
    }
    
    private int intSpeciesID;
    
    public String validateName(String strInput) {
       
        Pattern ptnName = Pattern.compile("[0-9]");
        Matcher mtcName = ptnName.matcher(strInput);
        if(mtcName.matches()) {
            return "Name format is invalid!";
        }
        return "";
    }
    
    private String validateSpeciesName(String strInput) {
        
        if(strInput.equals("")) {
            return "Species name cannot be null";
        } else if(!strInput.equals("")) {
            return validateName(strInput);
        }
        return "";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSpecies = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSpeciesName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblSpecies.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSpecies.setText("Species");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(192, 192, 192)
                        .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(lblSpecies)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSpecies)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(validateSpeciesName(txtSpeciesName.getText().trim()).equals("")) {
            
            if(Client.currentInstance().contactServer(new String[]{"SELECT * FROM Species WHERE SpeciesName ='"+
                    txtSpeciesName.getText().trim()+"'", "Check"})[0].equals("true")) { // Check if species is already added
                
                JOptionPane.showMessageDialog(this, "The species exist in the database", "WARNING", JOptionPane.WARNING_MESSAGE);
                txtSpeciesName.requestFocusInWindow();
                
            } else {
                // Send data to the server to add species and check if the output
                // recieved from the server confirms the species is added
                if(Client.currentInstance().contactServer(new String[]{"INSERT INTO Species (SpeciesName)VALUES('"+
                    txtSpeciesName.getText().trim()+"')", "Execute"})[0].equals("true")) { 
                    
                    JOptionPane.showMessageDialog(this, "Species added.", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, validateSpeciesName(txtSpeciesName.getText().trim()), 
                    "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(btnUpdate.getText().equals("Update")) {
            
            new ChooseRecord("SELECT SpeciesName FROM Species").setVisible(true);
            if(ChooseRecord.getOption() != null) {
                String[] arrSpeciesDetails = Client.currentInstance().contactServer(
                    new String[]{"SELECT SpeciesID, SpeciesName FROM Species WHERE "
                        + "SpeciesName ='"+ChooseRecord.getOption()+"'", "Row"});
            
                intSpeciesID = Integer.parseInt(arrSpeciesDetails[0]);
                txtSpeciesName.setText(arrSpeciesDetails[1]);
                btnUpdate.setText("Save..");
            }
            
            
            
        } else if(btnUpdate.getText().equals("Save..")) {
            if(validateSpeciesName(txtSpeciesName.getText()).equals("")) {
                // Checks if species is already in the database and it is not the same as the value that was initially
                // extracted from the database
                if(Client.currentInstance().contactServer(new String[]{"SELECT * FROM Species WHERE SpeciesName ='"+
                        txtSpeciesName.getText().trim()+"' AND SpeciesID <> "+intSpeciesID, "Check"})[0].equals("true")) { 
                
                    JOptionPane.showMessageDialog(this, "The species exist in the database", "WARNING", JOptionPane.WARNING_MESSAGE);
                    txtSpeciesName.requestFocusInWindow();
                    btnUpdate.setText("Update");
                
                } else {
                    if(Client.currentInstance().contactServer(
                        new String[]{"UPDATE Species SET SpeciesName ='"+
                                txtSpeciesName.getText().trim() + "' WHERE SpeciesID ="+
                                intSpeciesID, "Execute"})[0].equals("true")) {
                
                        JOptionPane.showMessageDialog(this, "Update successful", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                        btnUpdate.setText("Update");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtSpeciesName.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        txtSpeciesName.setText("");
        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSpecies;
    private javax.swing.JTextField txtSpeciesName;
    // End of variables declaration//GEN-END:variables
}
